### ISSUE TITLE
getReactNativeVersion() fails with undefined property access on package.json without dependencies

### ISSUE THREAD

**Issue by samuelneff** [microsoft/appcenter-cli#1485]
### **Description**

Our `package.json` file has no `dependencies` and doesn't even have this section. It has only `peerDependencies` and `devDependencies`.

When we try to run codepush it fails when trying to determine the version of React Native.

```
appcenter codepush release-react -a MyApp/my-app-android -d Staging --debug
```

I get this error:

```
Command Failure at TypeError: Cannot read property 'react-native' of undefined
    at Object.getReactNativeVersion (/Users/j0p011l/.nvm/versions/node/v12.18.3/lib/node_modules/appcenter-cli/dist/commands/codepush/lib/react-native-utils.js:417:44)
    at CodePushReleaseReactCommand.<anonymous> (/Users/j0p011l/.nvm/versions/node/v12.18.3/lib/node_modules/appcenter-cli/dist/commands/codepush/release-react.js:34:39)
    at Generator.next (<anonymous>)
    at /Users/j0p011l/.nvm/versions/node/v12.18.3/lib/node_modules/appcenter-cli/dist/commands/codepush/release-react.js:14:71
    at new Promise (<anonymous>)
    at __awaiter (/Users/j0p011l/.nvm/versions/node/v12.18.3/lib/node_modules/appcenter-cli/dist/commands/codepush/release-react.js:10:12)
    at CodePushReleaseReactCommand.run (/Users/j0p011l/.nvm/versions/node/v12.18.3/lib/node_modules/appcenter-cli/dist/commands/codepush/release-react.js:33:16)
    at CodePushReleaseReactCommand.runNoClient (/Users/j0p011l/.nvm/versions/node/v12.18.3/lib/node_modules/appcenter-cli/dist/util/commandline/command.js:112:25)
    at CodePushReleaseReactCommand.<anonymous> (/Users/j0p011l/.nvm/versions/node/v12.18.3/lib/node_modules/appcenter-cli/dist/util/commandline/command.js:75:25)
    at Generator.next (<anonymous>)
Error: Command 'codepush release-react -a Stock-Transfers/sto-ui-android-appcenter -d Staging --debug' failed with exception "Cannot read property 'react-native' of undefined"
```

Error is due to this line in `getReactNativeVersion()`

```
    return (projectPackageJson.dependencies["react-native"] ||
        (projectPackageJson.devDependencies && projectPackageJson.devDependencies["react-native"]));
```

It should be:

```
    return (
        (projectPackageJson.dependencies && projectPackageJson.dependencies["react-native"]) ||
        (projectPackageJson.devDependencies && projectPackageJson.devDependencies["react-native"])
    );
```

### **Repro Steps**
Please list the steps used to reproduce your issue.
1. Create new react-native project
2. Add dependencies to `devDependencies` only
3. Remove `dependencies` section from `package.json`
4. Run `appcenter codepush`

### **Expected behavior**

Expected new bundle to be pushed up to AppCenter.

### **Details**
1. Is there a particular beacon/command that you are having trouble with?
    - `appcenter codepush release-react`
2. Which version of the App Center CLI are you using?
    - `2.9.0`
3. Which OS version did you experience the issue on?
    - `macOS BigSur 11.4`
4. What command line/shell are you using?
    - `GNU bash, version 3.2.57(1)-release (x86_64-apple-darwin20)`
5. What version of Node.js and NPM/Yarn are you using?
    - `node v14.17.0`
    - `npm 6.14.13`
6. Additionally, you can provide verbose logs of a CLI command by using...
    - See stack trace in description

**Comment by AnastasiaKubova** [comment]
Hi! Thanks for getting in touch with us! I mark this issue as a bug and create a ticket on our board. But feel free to create contribution PR with a fix for it if you already have a solution.
