### ISSUE TITLE
Crashes on case sensitive file systems

### ISSUE THREAD

**Issue by kamstrup** [Microsoft/appcenter-cli#308]
PR here https://github.com/Microsoft/appcenter-cli/pull/307

```
kamstrup@mandrill:~$ appcenter 
module.js:538
    throw err;
    ^

Error: Cannot find module './generated/AppCenterClient'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/usr/lib/node_modules/appcenter-cli/dist/util/apis/create-client.js:6:25)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
```

**Comment by christav** [comment]
Fixed by #307, released in appcenter-cli@1.0.2. Thanks for the fix!
