### ISSUE TITLE
App Center Android Instrumented Tests Always Fail

### ISSUE THREAD

**Issue by michaeltnguyen** [Microsoft/appcenter-cli#396]
```
$ appcenter --version
appcenter version 1.0.11
```

I am using the app center sample android app here:  https://github.com/Microsoft/appcenter-sampleapp-android

There is a single test in the project.  I've modified this test so that it always passes.

```
@Test
public void useAppContext() throws Exception {
    assertTrue(true);
}
```

Running the espresso tests through the appcenter cli always marks the test suite as failed with the following output:

```
Current test status: Failed!
Reason: INSTRUMENTATION_STATUS: class=com.example.appcenter.sampleapp_android.ExampleInstrumentedTest
INSTRUMENTATION_STATUS: current=1
INSTRUMENTATION_STATUS: id=AndroidJUnitRunner
INSTRUMENTATION_STATUS: numtests=1
INSTRUMENTATION_STATUS: stream=
com.example.appcenter.sampleapp_android.ExampleInstrumentedTest:
INSTRUMENTATION_STATUS: test=useAppContext
INSTRUMENTATION_STATUS_CODE: 1
INSTRUMENTATION_STATUS: class=com.example.appcenter.sampleapp_android.ExampleInstrumentedTest
INSTRUMENTATION_STATUS: current=1
INSTRUMENTATION_STATUS: id=AndroidJUnitRunner
INSTRUMENTATION_STATUS: numtests=1
INSTRUMENTATION_STATUS: stream=.
INSTRUMENTATION_STATUS: test=useAppContext
INSTRUMENTATION_STATUS_CODE: 0
INSTRUMENTATION_RESULT: stream=

Time: 0.006

OK (1 test)


INSTRUMENTATION_CODE: -1
Error: Cannot run tests. Returning exit code 2.
```

The first line is suspicious, but you can see the `OK (1 test)`.  Before fixing the test, the output looks like this, so the test is clearly passing.

```
Time: 0.008
There was 1 failure:
1) useAppContext(com.example.appcenter.sampleapp_android.ExampleInstrumentedTest)
org.junit.ComparisonFailure: expected:<com.example.[tina].sampleapp_android> but was:<com.example.[appcenter].sampleapp_android>
	at org.junit.Assert.assertEquals(Assert.java:115)
	at org.junit.Assert.assertEquals(Assert.java:144)
	at com.example.appcenter.sampleapp_android.ExampleInstrumentedTest.useAppContext(ExampleInstrumentedTest.java:24)
	at java.lang.reflect.Method.invoke(Native Method)
	at org.junit.runners.model.FrameworkMethod$1.runReflectiveCall(FrameworkMethod.java:50)
	at org.junit.internal.runners.model.ReflectiveCallable.run(ReflectiveCallable.java:12)
	at org.junit.runners.model.FrameworkMethod.invokeExplosively(FrameworkMethod.java:47)
	at org.junit.internal.runners.statements.InvokeMethod.evaluate(InvokeMethod.java:17)
	at org.junit.runners.ParentRunner.runLeaf(ParentRunner.java:325)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:78)
	at org.junit.runners.BlockJUnit4ClassRunner.runChild(BlockJUnit4ClassRunner.java:57)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runners.Suite.runChild(Suite.java:128)
	at org.junit.runners.Suite.runChild(Suite.java:27)
	at org.junit.runners.ParentRunner$3.run(ParentRunner.java:290)
	at org.junit.runners.ParentRunner$1.schedule(ParentRunner.java:71)
	at org.junit.runners.ParentRunner.runChildren(ParentRunner.java:288)
	at org.junit.runners.ParentRunner.access$000(ParentRunner.java:58)
	at org.junit.runners.ParentRunner$2.evaluate(ParentRunner.java:268)
	at org.junit.runners.ParentRunner.run(ParentRunner.java:363)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:137)
	at org.junit.runner.JUnitCore.run(JUnitCore.java:115)
	at android.support.test.internal.runner.TestExecutor.execute(TestExecutor.java:59)
	at android.support.test.runner.AndroidJUnitRunner.onStart(AndroidJUnitRunner.java:262)
	at android.app.Instrumentation$InstrumentationThread.run(Instrumentation.java:2075)

FAILURES!!!
Tests run: 1,  Failures: 1

INSTRUMENTATION_CODE: -1
Error: Cannot run tests. Returning exit code 2.
```

Here is where the failure message is generated:

https://github.com/Microsoft/appcenter-cli/blob/master/src/commands/test/lib/run-tests-command.ts#L125

The exit code is generating by making an api call, so I'm guessing that the API is returning an erroneous result.

**Comment by john7doe** [comment]
Michael,

It looks like you did not complete the step in section 2 https://docs.microsoft.com/da-dk/appcenter/test-cloud/preparing-for-upload/espresso#2-changes-to-the-tests. Without the ReportHelper its impossible for us to produce a test rapport and we fail the test run as an result. 

Br,
/Simon

**Comment by michaeltnguyen** [comment]
Hi Simon,

This worked, thanks.  The documents seemed to indicate that the report helper was an optional step (I didn't want to do any extra labeling).  Appreciate the help!

Michael
