### ISSUE TITLE
Running `test run uitest` with `--merge-nunit-xml` flag in a Windows env fails with "Error: Couldn't merge xml test results to <filename>"

### ISSUE THREAD

**Issue by SimpsOff** [microsoft/appcenter-cli#493]
AppCenter v1.1.4 through 1.1.0 all attempted, with the same issue.
Node v8.12.0 (windows personal env), v8.11.1 (windows build server), v9.10.1 (mac OS env)

As the title states, running a `uitest` with the `--merge-nunit-xml` flag from a Windows OS fails with "Error: Couldn't merge xml test results to results.xml"

Example command:
```
"C:\ProgramData\nodejs\appcenter.cmd" test run uitest     --store-path "C:\BuildAgent\work\52fe272bfade4750\Example.Android\keystore"     --store-password *******     --key-alias test     --key-password *******     --app-path "C:\BuildAgent\work\52fe272bfade4750\Example.Android\bin\Release\Example.apk"     --app "ExampleAppName"     --build-dir "C:\BuildAgent\work\52fe272bfade4750\Example.UITests\bin\Debug"     --devices "exampleDevices"     --test-chunk     --token exampletoken     --test-series "smoke-test"     --include-category "SmokeTest"     --locale "en_US"     --test-output-dir "C:\BuildAgent\work\52fe272bfade4750\Example.UITests\obj\Debug"     --merge-nunit-xml results.xml     --debug
```

After building and running the test suite on Windows with the latest from `master` and also the code from `v1.1.4`, two unit tests fail:

```
  1) junit xml util
       should combine xmls correctly:

      AssertionError: expected 1 to deeply equal 2
      + expected - actual

      -1
      +2

      at Suite.<anonymous> (test\commands\test\util\junit-xml-util-test.ts:138:34)
      at Generator.next (<anonymous>)
      at fulfilled (test\commands\test\util\junit-xml-util-test.ts:4:58)
      at <anonymous>

  2) nunit xml util
       should combine xmls correctly:
     Error: Start tag expected, '<' not found

      at Object.module.exports.fromXml (node_modules\libxmljs\lib\document.js:168:21)
      at Suite.<anonymous> (test\commands\test\util\nunit-xml-util-test.ts:147:12)
      at Generator.next (<anonymous>)
      at fulfilled (test\commands\test\util\nunit-xml-util-test.ts:4:58)
      at <anonymous>
```

These unit tests don't fail when run from OSX, so it seems platform specific and related to the file system, but I couldn't figure out how to work around it. Any help would be appreciated since our build server that runs these tests is a Windows machine. =]

**Comment by AndreyMitsyk** [comment]
Hi @SimpsOff 
Could you please provide your node js version on Windows machine?

**Comment by AndreyMitsyk** [comment]
@SimpsOff We will investigate this. Is it possible for you to try NodeJS 9 with appcenter CLI?

**Comment by SimpsOff** [comment]
@AndreyMitsyk  I've installed v9.10.1 on my local Windows machine, same as i had on my mac, running `npm test` after this update also still yields errors.

The first test run, i hit:
```
  198 passing (2s)
  2 failing

  1) nunit xml util
       should combine xmls correctly:
     Error: Start tag expected, '<' not found

      at Object.module.exports.fromXml (node_modules\libxmljs\lib\document.js:168:21)
      at Suite.<anonymous> (test\commands\test\util\nunit-xml-util-test.ts:147:12)
      at Generator.next (<anonymous>)
      at fulfilled (test\commands\test\util\nunit-xml-util-test.ts:4:58)
      at <anonymous>

  2) nunit xml util
       should throw an explicit exception:

      AssertionError: expected false to deeply equal true
      + expected - actual

      -false
      +true

      at Suite.<anonymous> (test\commands\test\util\nunit-xml-util-test.ts:163:26)
      at Generator.next (<anonymous>)
      at fulfilled (test\commands\test\util\nunit-xml-util-test.ts:4:58)
      at <anonymous>
```
and i also tried running the tests again, somewhat surprisingly i got different results:
```
  197 passing (2s)
  3 failing

  1) junit xml util
       should combine xmls correctly:

      AssertionError: expected '4' to deeply equal '6'
      + expected - actual

      -4
      +6

      at Suite.<anonymous> (test\commands\test\util\junit-xml-util-test.ts:151:32)
      at Generator.next (<anonymous>)
      at fulfilled (test\commands\test\util\junit-xml-util-test.ts:4:58)
      at <anonymous>

  2) junit xml util
       should throw an explicit exception:

      AssertionError: expected false to deeply equal true
      + expected - actual

      -false
      +true

      at Suite.<anonymous> (test\commands\test\util\junit-xml-util-test.ts:186:26)
      at Generator.next (<anonymous>)
      at fulfilled (test\commands\test\util\junit-xml-util-test.ts:4:58)
      at <anonymous>

  3) nunit xml util
       should combine xmls correctly:
     Error: Start tag expected, '<' not found

      at Object.module.exports.fromXml (node_modules\libxmljs\lib\document.js:168:21)
      at Suite.<anonymous> (test\commands\test\util\nunit-xml-util-test.ts:147:12)
      at Generator.next (<anonymous>)
      at fulfilled (test\commands\test\util\nunit-xml-util-test.ts:4:58)
      at <anonymous>
```

I'm not a node expert by any means, but this definitely points to a platform specific race condition to me, i wish i knew enough about how to fix it though.

Now, for these two runs, i used v0.19.5 of (https://github.com/libxmljs/libxmljs/releases) since the referenced v0.18.8 wouldn't install properly after i updated node on my windows machine with a simple `npm install`. Not sure if that helps or not, but let me know if there's any more info i can provide for you.

**Comment by owenniblock** [comment]
@SimpsOff - we've changed the dependency we were using for unzipping the download and also fixed some intermittent issues with timings on streamed files from within the zip (which weren't apparent on some device / OS combinations) - please could you retry this with the latest `appcenter-cli` and let us know if it's still happening on your dev set-up?

Thanks!

**Comment by amchew** [comment]
@SimpsOff checking back in, would you be able to test it and see if you're still facing an issue? Thanks!

**Comment by ahdbilal** [comment]
Closing this issue because of no response. Please feel free to reopen it if the issue still persists.
