### ISSUE TITLE
Error: ETIMEDOUT on symbols upload

### ISSUE THREAD

**Issue by ufna** [Microsoft/appcenter-cli#563]
Once symbol files became ~350Mb size I've met this error:

```
Using appcenter-cli version: 1.1.13
logFilter, request: {
  "rawResponse": false,
  "queryString": {},
  "url": "https://api.appcenter.ms/v0.1/apps/TEAM/APP/symbol_uploads",
  "method": "POST",
  "headers": {
    "Content-Type": "application/json; charset=utf-8",
    "user-agent": "appcenterCli/1.1.13 NodeJS/v8.15.1 linux/4.4.0-142-generic",
    "x-api-token": "xxx"
  },
  "body": "{\"symbol_type\":\"Apple\"}"
}
Response status code: 500
Body: {"message":"internal error","err_message":"ETIMEDOUT","err_stack":"Error: ETIMEDOUT\n    at Timeout._onTimeout (/home/node/data/node_modules/request/request.js:759:15)\n    at ontimeout (timers.js:498:11)\n    at tryOnTimeout (timers.js:323:5)\n    at Timer.listOnTimeout (timers.js:290:5)"}
```

Is it something temporary with server, or I need to adjust timeout somehow?

**Comment by ufna** [comment]
Fixed now
