### ISSUE TITLE
exception "Forbidden"

### ISSUE THREAD

**Issue by mirik999** [Microsoft/appcenter-cli#577]
appcenter codepush release-react -a mirik999/appName -d Production --debug
Using appcenter-cli version: 1.1.15
logFilter, request: {
  "rawResponse": false,
  "queryString": {},
  "url": "https://api.appcenter.ms/v0.1/apps/mirik999/appName/deployments/Production",
  "method": "GET",
  "headers": {
    "Content-Type": "application/json; charset=utf-8",
    "user-agent": "appcenterCli/1.1.15 NodeJS/v10.15.3 win32/10.0.17763",
    "x-api-token": "token"
  },
  "body": null
}
Response status code: 403
Body: {"message":"Forbidden","code":"Forbidden"}
Command Failure at Error: Forbidden
    at client.pipeline (C:\Users\mirik\AppData\Roaming\npm\node_modules\appcenter-cli\dist\util\apis\generated\operations\codePushDeployment
s.js:378:19)
    at retryCallback (C:\Users\mirik\AppData\Roaming\npm\node_modules\appcenter-cli\node_modules\ms-rest\lib\filters\systemErrorRetryPolicyF
ilter.js:89:9)
    at retryCallback (C:\Users\mirik\AppData\Roaming\npm\node_modules\appcenter-cli\node_modules\ms-rest\lib\filters\exponentialRetryPolicyF
ilter.js:140:9)
    at C:\Users\mirik\AppData\Roaming\npm\node_modules\appcenter-cli\node_modules\ms-rest\lib\filters\rpRegistrationFilter.js:59:14
    at handleRedirect (C:\Users\mirik\AppData\Roaming\npm\node_modules\appcenter-cli\node_modules\ms-rest\lib\filters\redirectFilter.js:39:9
)
    at C:\Users\mirik\AppData\Roaming\npm\node_modules\appcenter-cli\node_modules\ms-rest\lib\filters\formDataFilter.js:23:14
    at C:\Users\mirik\AppData\Roaming\npm\node_modules\appcenter-cli\node_modules\ms-rest\lib\filters\logFilter.js:21:14
    at Request.defaultRequest [as _callback] (C:\Users\mirik\AppData\Roaming\npm\node_modules\appcenter-cli\node_modules\ms-rest\lib\request
Pipeline.js:125:16)
    at Request.self.callback (C:\Users\mirik\AppData\Roaming\npm\node_modules\appcenter-cli\node_modules\request\request.js:185:22)
    at Request.emit (events.js:189:13)
Error: Command 'codepush release-react -a mirik999/appName -d Production --debug' failed with exception "Forbidden"

**Comment by mirik999** [comment]
i fixed it, my mistake.

**Comment by jmhinric** [comment]
@mirik999 what was your issue?  I'm hitting the same error in trying to use codepush for the first time with an app.

**Comment by jmhinric** [comment]
Figured it out- our README had the wrong app name.  To get the correct app name, use `appcenter apps list`.
