### ISSUE TITLE
Travis CI file watcher error

### ISSUE THREAD

**Issue by OzzieOrca** [microsoft/appcenter-cli#590]
We're running the codepush cli commands in a non sudo Travis CI build and getting an error about file watchers. Is there a way to get the React/Codepush bundler not to use file watchers? I didn't see any related flags on `appcenter codepush release-react` or `react-native bundle`. Here's the relevant section of the Travis logs:

```
Build system information
Build language: node_js
Build group: stable
Build dist: trusty
...
Runtime kernel version: 4.4.0-101-generic
travis-build version: 11415f344
...
Operating System Details
Distributor ID:	Ubuntu
Description:	Ubuntu 14.04.5 LTS
Release:	14.04
Codename:	trusty

...

$ node --version
v11.15.0
$ npm --version
6.7.0
$ nvm --version
0.34.0
$ yarn --version
1.3.2

...

$ appcenter codepush release-react -a MyOrg/MyApp-iOS --plist-file ios/MyApp/Info.plist --token [secure] --sourcemap-output sourcemap.ios.js --extra-bundler-option=--sourcemap-sources-root --extra-bundler-option=./ --description 'MyCommit'
Detecting ios app version:
Using the target binary version value "5.1.1" from "ios/MyApp/Info.plist".
Running "react-native bundle" command:
node node_modules/react-native/local-cli/cli.js bundle --assets-dest /tmp/code-push119418-9929-zpoim4.3uhug/CodePush --bundle-output /tmp/code-push119418-9929-zpoim4.3uhug/CodePush/main.jsbundle --dev false --entry-file index.js --platform ios --sourcemap-sources-root ./ --sourcemap-output sourcemap.ios.js
internal/fs/watchers.js:173
    throw error;
    ^
Error: ENOSPC: System limit for number of file watchers reached, watch '/home/travis/build/MyOrg/MyApp-react-native/node_modules/rollbar-react-native/android/build/tmp/expandedArchives/classes.jar_4wtwpknpsrx8513u10zz514dn/com/facebook/imagepipeline/decoder'
    at FSWatcher.start (internal/fs/watchers.js:165:26)
    at Object.watch (fs.js:1274:11)
    at NodeWatcher.watchdir (/home/travis/build/MyOrg/MyApp-react-native/node_modules/metro/node_modules/sane/src/node_watcher.js:159:22)
    at Walker.<anonymous> (/home/travis/build/MyOrg/MyApp-react-native/node_modules/metro/node_modules/sane/src/common.js:109:31)
    at Walker.emit (events.js:193:13)
    at /home/travis/build/MyOrg/MyApp-react-native/node_modules/walker/lib/walker.js:69:16
    at go$readdir$cb (/home/travis/build/MyOrg/MyApp-react-native/node_modules/graceful-fs/graceful-fs.js:162:14)
    at FSReqCallback.args [as oncomplete] (fs.js:145:20)
Error: Failed to release a CodePush update.
error Command failed with exit code 3.
```

Package versions:
```
appcenter-cli: 1.1.15
react-native: 0.59.4
@react-native-community/cli: 1.6.0
```

All the fixes I've seen for file watcher errors involve sudo. I'd rather not run our build as sudo...

Thanks for your help :)

**Comment by DmitriyKirakosyan** [comment]
As we do not have plans to fix this issue for this feature in the next year, I'm closing the issue.
