### ISSUE TITLE
CodePush failed to release cause node try to exec shell script

### ISSUE THREAD

**Issue by nandafirmans** [microsoft/appcenter-cli#759]
please help I can't release my react-native app. check me if I'm wrong, I expecting this failed cause node try to exec shell script

I'm running on windows 10 
* nodejs ```10.15.3```
* react-native ```0.61.5```
* appcenter-cli ```2.3.4```

```
appcenter codepush release-react  -a mypesantrenpos/MyPesantren -e .\index.ts -d Staging


Running "react-native bundle" command:

node node_modules\.bin\react-native bundle --assets-dest C:\Users\USER\AppData\Local\Temp\code-push2020219-4324-1v4gpck.427i\CodePush --bundle-output C:\Users\USER\AppData\Local\Temp\code-push2020219-4324-1v4gpck.427i\CodePush\index.android.bundle --dev false --entry-file .\index.ts --platform android
D:\Nanda\Tugas\my-pesantren\MyPesantren\node_modules\.bin\react-n
ative:2
basedir=$(dirname "$(echo "$0" | sed -e 's,\\,/,g')")
          ^^^^^^^

SyntaxError: missing ) after argument list
    at new Script (vm.js:80:7)
    at createScript (vm.js:274:10)
    at Object.runInThisContext (vm.js:326:10)
    at Module._compile (internal/modules/cjs/loader.js:664:28)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoa
d (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
Error: Failed to release a CodePush update.
```

**Comment by nandafirmans** [comment]
its working on appcenter-cli version 2.3.3

on version 2.3.3 ```react-native bundle``` run with command : 
```node node_modules\react-native\local-cli\cli.js bundle```

but on version 2.3.4 run with this command: 
```node node_modules\.bin\react-native bundle```
which is not working on windows I think..

**Comment by guilhermegonzaga** [comment]
Same problem here

**Comment by alz10** [comment]
@nandafirmans appcenter v2.3.3 works for me, thanks

**Comment by jp-andre** [comment]
Hi! Thanks all for reporting this issue, we will look into it.
