### ISSUE TITLE
List branches command for builds fail with APPCENTER_API_TOKEN set

### ISSUE THREAD

**Issue by kevjett** [microsoft/appcenter-cli#844]
I'm trying to call 'appcenter build branches list' command and it fails and says 

```
Error: Command 'build branches list' failed with exception "Cannot read property 'defaultApp' of null"
```

I've seen in some other tickets that this was usually caused by a bug that didn't use the token parameter or environment variable.

Here's the debug info for the call.

```
# appcenter build branches list --debug
Using appcenter-cli version: 2.5.0
Command Failure at TypeError: Cannot read property 'defaultApp' of null
    at ShowBranchesListBuildStatusCommand.get app [as app] (/usr/local/lib/node_modules/appcenter-cli/dist/util/commandline/app-command.js:39:25)
    at ShowBranchesListBuildStatusCommand.<anonymous> (/usr/local/lib/node_modules/appcenter-cli/dist/commands/build/branches/list.js:28:30)
    at Generator.next (<anonymous>)
    at /usr/local/lib/node_modules/appcenter-cli/dist/commands/build/branches/list.js:14:71
    at new Promise (<anonymous>)
    at __awaiter (/usr/local/lib/node_modules/appcenter-cli/dist/commands/build/branches/list.js:10:12)
    at ShowBranchesListBuildStatusCommand.run (/usr/local/lib/node_modules/appcenter-cli/dist/commands/build/branches/list.js:27:16)
    at ShowBranchesListBuildStatusCommand.runNoClient (/usr/local/lib/node_modules/appcenter-cli/dist/util/commandline/command.js:111:25)
    at ShowBranchesListBuildStatusCommand.<anonymous> (/usr/local/lib/node_modules/appcenter-cli/dist/util/commandline/command.js:74:25)
    at Generator.next (<anonymous>)
Error: Command 'build branches list --debug' failed with exception "Cannot read property 'defaultApp' of null"
```

Same thing happens if I use the --token parameter.

**Comment by anywherepilot** [comment]
To get actual debug output you need to set the `DEBUG` environment variable: https://github.com/microsoft/appcenter-cli/blob/master/contributing.md#enabling-debug-logs

If you get this error, it must mean `profile` is `null` [here](https://github.com/microsoft/appcenter-cli/blob/master/src/util/commandline/app-command.ts#L38). This is the case when you did not run `appcenter login` before (and don't have a profile.json file in your config directory). The only way that can pass [these](https://github.com/microsoft/appcenter-cli/blob/master/src/util/commandline/command.ts#L159) checks is if you specify a token through an environment variable. This means you must have the `APPCENTER_ACCESS_TOKEN` environment variable set to your API token.

If I do the same thing, the code indeed fails there in this manner. It needs a null check. I'll add it. You will then get this error instead:

`Could not find application to work on. Specify the '--app' switch, use 'appcenter apps set-current', or set the MOBILE_CENTER_CURRENT_APP environment variable.`

**Comment by anywherepilot** [comment]
Thank you for reporting this @kevjett. I found the same problem in three other places.
